// Generated by https://quicktype.io

import { Pokemon } from "src/pokemon/entities/pokemon.entity";

export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
